name: Deploy Databricks Job

on:
  push:
    branches:
      - develop

env:
  DATABRICKS_TOKEN: ${{secrets.ONE_ENV_TOKEN}}
  DATABRICKS_HOST: https://dbc-e0d9a449-b7e7.cloud.databricks.com/

jobs:
  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Databricks CLI
        run: |
          pip install databricks-cli jq

      - name: Copy DLT Meta Config files
        run: |
          databricks fs cp -r conf/ dbfs:/Volumes/harsha_pasala/default/data/conf/

      - name: Create Databricks Job
        id: create_job
        run: |
          JOB_OUTPUT=$(databricks jobs create --json "$(cat setup/onboarding_job.json)")
          echo "$JOB_OUTPUT"
          JOB_ID=$(echo "$JOB_OUTPUT" | jq -r '.job_id')
          echo "job_id=$JOB_ID" >> "$GITHUB_OUTPUT"

      - name: Use Job ID
        run: |
          echo "Created job ID: ${{ steps.create_job.outputs.job_id }}"
